name: Deploy Staging

on: 
  push:
    branches:
      - next   
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: next
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - uses: azure/docker-login@v1
        with:
          login-server: wmcontainers.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Building Docker Image
        working-directory: ./src/ShawnLink
        run: docker build . -t wmcontainers.azurecr.io/shawnlink:next

      - name: Push the Image
        working-directory: ./src/ShawnLink 
        run: docker push wmcontainers.azurecr.io/shawnlink:next
